### ISSUE TITLE
Navigation and back gesture unresponsive [BUG] 

### ISSUE THREAD

**Issue by usamaiqbal1177** [Goooler/LawnchairRelease#57] opened 2024-03-01 20:16 UTC
### Describe the bug

Sometimes the navigation bar gestures and back gestures doesn't work or the current app becomes unresponsive. In that case, I have to press swipe up on nav bar a couple of times and then it goes to home screen...

This is quote frequent and happens very randomly.

Pixel 8 Pro stock android 14 February

**Comment by Goooler** [comment] 2024-03-02 11:56
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/4050

**Closed by Goooler** 2024-03-02 11:56 UTC
Labels: bug
